package mailer

import (
	"encoding/base64"
	"fmt"
	"os"

	"github.com/sendgrid/sendgrid-go"
	"github.com/sendgrid/sendgrid-go/helpers/mail"
	"payroll-backend/internal/models"
)

// email the password-protected PDF to the employees
func SendSalarySlip(emp models.Employee, pdfPath string, month string) error {
	apiKey := os.Getenv("SENDGRID_API_KEY")
	fromEmail := os.Getenv("SENDGRID_FROM_EMAIL")

	if apiKey == "" || fromEmail == "" {
		return fmt.Errorf("SENDGRID_API_KEY or SENDGRID_FROM_EMAIL not set in .env")
	}

	// Read & Base64 encode the PDF for attachment
	pdfData, err := os.ReadFile(pdfPath)
	if err != nil {
		return fmt.Errorf("failed to read PDF: %v", err)
	}
	encodedPDF := base64.StdEncoding.EncodeToString(pdfData)

	from := mail.NewEmail("Nippon Toyota HR", fromEmail)
	to := mail.NewEmail(emp.Name, emp.Email)
	subject := fmt.Sprintf("Your %s Salary Slip - Nippon Toyota", month)

	htmlBody := fmt.Sprintf(`
		<div style="background-color: #f1f5f9; padding: 40px 20px; font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif;">
			<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%%" style="max-width: 600px; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);">
				<!-- Top Accent Line -->
				<tr>
					<td style="background-color: #eb0a1e; height: 4px;"></td>
				</tr>
				<!-- Header -->
				<tr>
					<td style="padding: 40px 40px 30px 40px; text-align: left; border-bottom: 1px solid #f1f5f9;">
						<h1 style="color: #0f172a; margin: 0; font-size: 24px; font-weight: 800; letter-spacing: -0.5px;">NIPPON TOYOTA</h1>
						<p style="color: #64748b; margin: 6px 0 0 0; font-size: 12px; font-weight: 600; letter-spacing: 1.5px; text-transform: uppercase;">Confidential Payroll Document</p>
					</td>
				</tr>
				<!-- Body -->
				<tr>
					<td style="padding: 40px; color: #334155; line-height: 1.6;">
						<p style="font-size: 16px; margin-top: 0; color: #0f172a;">Dear <strong style="color: #0f172a;">%s</strong>,</p>
						<p style="font-size: 16px;">Please find attached your official salary slip for the month of <strong>%s</strong>. This document has been securely generated by the Nippon Toyota Automated Payroll System.</p>
						
						<!-- Security Notice -->
						<div style="margin: 35px 0; padding: 25px; background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px;">
							<div style="display: flex; align-items: center; margin-bottom: 12px;">
								<span style="font-size: 18px; margin-right: 8px;">🔒</span>
								<h3 style="margin: 0; color: #0f172a; font-size: 15px; font-weight: 700;">AES-256 Document Security</h3>
							</div>
							<p style="margin: 0 0 12px 0; font-size: 14px; color: #475569; line-height: 1.5;">To protect your personal financial data, the attached PDF is securely encrypted. You will need to enter your designated password to view the contents.</p>
							<div style="background-color: #ffffff; padding: 12px 16px; border-radius: 4px; border: 1px dashed #cbd5e1;">
								<p style="margin: 0; font-size: 13px; color: #64748b;"><strong>Password Format:</strong> First Name + Birth Year</p>
								<p style="margin: 4px 0 0 0; font-size: 13px; color: #0f172a; font-family: monospace;">Example: Shiva2004</p>
							</div>
						</div>
						
						<p style="font-size: 14px; color: #64748b;">If you notice any discrepancies in your pay or have trouble opening the document, please contact your regional HR representative.</p>
						<br/>
						<p style="font-size: 15px; margin-bottom: 0;">Sincerely,</p>
						<p style="font-size: 15px; font-weight: 600; margin-top: 4px; color: #0f172a;">Human Resources Department<br/><span style="color: #64748b; font-weight: 400; font-size: 14px;">Nippon Toyota Motors</span></p>
					</td>
				</tr>
				<!-- Footer -->
				<tr>
					<td style="background-color: #f8fafc; padding: 24px 40px; text-align: center; border-top: 1px solid #f1f5f9;">
						<p style="color: #94a3b8; font-size: 12px; margin: 0;">&copy; 2026 Nippon Toyota Motors. All rights reserved.</p>
						<p style="color: #94a3b8; font-size: 11px; margin: 6px 0 0 0;">This is an automated system email. Replies to this address are not monitored.</p>
					</td>
				</tr>
			</table>
		</div>
	`, emp.Name, month)

	// trying to override spam detection
	plainTextBody := fmt.Sprintf(`Dear %s,

This email contains your official confidential salary slip for the month of %s. 

Please find the document attached to this email as a secure PDF file. This document details your base salary, deductions, and net pay for the specified period. We advise you to review the contents carefully and keep this document for your personal financial records.

SECURITY NOTICE: 
To protect your privacy, your salary slip is securely encrypted with AES-256 bit encryption. To unlock and view the attached PDF, you must use your First Name followed by your Birth Year as the password. 

Example format: Shiva2004

If you have any questions, encounter issues opening your document, or notice any discrepancies in your pay, please contact the HR department directly.

Best regards,
Human Resources
Nippon Toyota
`, emp.Name, month)

	message := mail.NewSingleEmail(from, subject, to, plainTextBody, htmlBody)

	attachment := mail.NewAttachment()
	attachment.SetContent(encodedPDF)
	attachment.SetType("application/pdf")
	attachment.SetFilename(fmt.Sprintf("%s_Salary_Slip_%s.pdf", emp.EmployeeID, month))
	attachment.SetDisposition("attachment")
	message.AddAttachment(attachment)

	client := sendgrid.NewSendClient(apiKey)
	response, err := client.Send(message)
	if err != nil {
		return fmt.Errorf("SendGrid error: %v", err)
	}
	if response.StatusCode >= 400 {
		return fmt.Errorf("SendGrid rejected (status %d): %s", response.StatusCode, response.Body)
	}

	return nil
}
